regressiondata=read.csv(file.choose())
reg1 <- lm(regressiondata$Gower.s~regressiondata$Logdist)
reg2 <- lm(regressiondata$Gower.s2~regressiondata$Logdist2)
summary(reg1)
summary(reg2)
png(file="Ecoregionreg.png",width=6,height=7,units="in",res=500)
plot(regressiondata$Logdist, regressiondata$Gower.s,
     xlim=c(0,4), ylim=c(0,0.35), cex.main=2,col="darkgray", frame.plot=FALSE,ann=FALSE)
points(regressiondata$Logdist2,regressiondata$Gower.s2,col="black")
abline(reg1,col = "black",lty=2)
abline(reg2,col= "black",lty=1)
dev.off()

regressiondata2=read.csv(file.choose())
reg3 <- lm(regressiondata2$gowers1~regressiondata2$logdist1)
reg4 <- lm(regressiondata2$gowers2~regressiondata2$logdist2)
reg5 <- lm(regressiondata2$gowers3~regressiondata2$logdist3)
reg6 <- lm(regressiondata2$gowers4~regressiondata2$logdist4)
reg7 <- lm(regressiondata2$gowers5~regressiondata2$logdist5)

summary(reg3)
summary(reg4)
summary(reg5)
summary(reg6)
summary(reg7)


png(file="Ecoregionreg2.png",width=6,height=7,units="in",res=500)
plot(regressiondata2$logdist2, regressiondata2$gowers2,
     xlim=c(0,4), ylim=c(0,0.35), cex.main=2,col="darkgray", frame.plot=FALSE,ann=FALSE)
#points(regressiondata2$logdist1,regressiondata2$gowers1,col="black")
points(regressiondata2$logdist3,regressiondata2$gowers3,col="blue")
points(regressiondata2$logdist5,regressiondata2$gowers5,col="brown1")
points(regressiondata2$logdist4,regressiondata2$gowers4,col="yellow")
#abline(reg3,col = "black")
abline(reg4,col= "black",lty=2)
abline(reg5,col = "blue3")
abline(reg6,col= "gold")
abline(reg7,col= "firebrick1")
dev.off()
